filesystem:
  - name: children
    type: hstore
  - name: entityid
    type: int4
  - name: patty
    type: beef
groups:
  - name: uid
    type: int4
  - name: name
    type: varcha
  - name: permission
    type: permissions_enum
cheese_burgers:
  - name: patty
    type: beef