# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main, prototype, "renovate/*"]
  pull_request:
    branches: [main, prototype]

env:
  PG_PORT: 5432

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  backend_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: Building docker containers using docker-compose
        run: GO_MOD=go.mod docker-compose up -d --build
      - name: Golang Tests
        run: go test -v ./...
        working-directory: ./Backend
  frontend_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: type check
        run: cd Frontend && npm install && npm run types
      - name: react tests
        run: cd Frontend && npm test
